package sys

const (
	SERVERIMG         string = "https://app.ipsfa.gob.ve/imagenes/"
	CBASE             string = "sssifanb"
	CTIM              string = "tim"
	CESTADO           string = "estado"
	CMILITAR          string = "militar"
	CFAMILIAR         string = "familiar"
	CPERSONA          string = "persona"
	CCOMPONENTE       string = "componente"
	CRECIBO           string = "recibo"
	CINTEGRAL         string = "cuidadointegral"
	CREEMBOLSO        string = "reembolso"
	CAPOYO            string = "apoyo"
	CCARTAAVAL        string = "cartaaval"
	CFACTURA          string = "factura"
	CFEVIDA           string = "fevida"
	CTRATAMIENTO      string = "tratamiento"
	CTRAZA            string = "traza"
	CTRAZACIS         string = "trazacis"
	CCATEGORIA        string = "categoria"
	CUSUARIO          string = "usuario"
	WUSUARIO          string = "wusuario"
	CREDUCCION        string = "reduccion"
	CTAREASPENDIENDTE string = "tareaspendientes"
	CCONCEPTO         string = "conceptos"
	CMEDIDAJUDICIAL   string = "medidajudicial"
)
